version: '3.8'

services:
  mongodb:
    image: mongo:7
    container_name: designli-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_DATABASE: designli-stocks

  backend:
    build: ./backend
    container_name: designli-backend
    ports:
      - '3000:3000'
    env_file: ./backend/.env
    environment:
      MONGO_URI: mongodb://mongodb:27017/designli
    volumes:
      - ./backend/firebase-service-account.json:/app/firebase-service-account.json:ro
    depends_on:
      - mongodb
    restart: unless-stopped

volumes:
  mongo-data:
